#!/bin/sh

set -e

RECCE7_PATH=/usr/sbin/recce7/
RECCE7_DB=/usr/lib/recce7/honeyDB/
RECCE7_LOG=/usr/sbin/recce7/recce7.log
RECCE7_REPORT_SERVER=/bin/startReportServer.sh

if [ ! -d $RECCE7_DB ]; then
    mkdir -p $RECCE7_DB
    chmod 777 $RECCE7_DB
fi

mkdir -p $RECCE7_PATH
mkdir -p /var/local/recce7

if [ ! -f $RECCE7_LOG ]; then
    touch $RECCE7_LOG
    chown nobody:nobody $RECCE7_LOG
    chmod 666 $RECCE7_LOG
fi

echo Building p0f...
wget http://lcamtuf.coredump.cx/p0f3/releases/p0f-3.09b.tgz
tar zxvf p0f-3.09b.tgz
cd p0f-3.09b
./build.sh

echo Installing p0f to /usr/local/bin/ ...
sudo mkdir -p /usr/local/share/p0f
sudo cp ./p0f.fp /usr/local/share/p0f
sudo cp ./p0f /usr/sbin

echo "Creating report server script at $RECCE7_REPORT_SERVER"
if [ ! -f $RECCE7_REPORT_SERVER ]; then
    touch $RECCE7_REPORT_SERVER
    chmod 755 $RECCE7_REPORT_SERVER
    echo "#!/bin/bash" >> $RECCE7_REPORT_SERVER
    echo "export RECCE7_PLUGIN_CONFIG=/etc/recce7/configs/plugins.cfg" >> $RECCE7_REPORT_SERVER
    echo "export RECCE7_GLOBAL_CONFIG=/etc/recce7/configs/global.cfg" >> $RECCE7_REPORT_SERVER
    echo "RECCE7_PATH=/usr/sbin/recce7" >> $RECCE7_REPORT_SERVER
    echo "cd $RECCE7_PATH" >> $RECCE7_REPORT_SERVER
    echo "python3 -m reportserver.server.main" >> $RECCE7_REPORT_SERVER
fi

echo Building authbind
wget http://ftp.debian.org/debian/pool/main/a/authbind/authbind_2.1.1.tar.gz
tar xvzf authbind_2.1.1.tar.gz
cd authbind-2.1.1
make
make install

echo "Setting up authbind for privleged ports 22, 23, 80, and 443"
touch /etc/authbind/byport/22
touch /etc/authbind/byport/23
touch /etc/authbind/byport/80
touch /etc/authbind/byport/443
chown nobody:nobody /etc/authbind/byport/*
chmod 777 /etc/authbind/byport/*

echo Installing pip
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py

echo \(Py3\) Installing dateutil...
pip3 install python-dateutil
echo \(Py3\) Installing requests...
pip3 install requests
echo \(Py3\) Installing p0f API module...
sudo pip3 install p0f

